version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask  # Seu Dockerfile para o Flask
    ports:
      - "5000:5000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit  # Seu Dockerfile para o Streamlit
    ports:
      - "8501:8501"
